version: "3.9"
services:
  backend:
    build: ./backend
    image: piyush20062004/ai-backend:latest
    container_name: ai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: always
  frontend:
    build: ./frontend
    image: piyush20062004/ai-frontend:latest
    container_name: ai-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
