apiVersion: v1
kind: Service
metadata:
  name: ai-backend-service
  namespace: langgraph-env
spec:
  type: ClusterIP
  selector:
    app: ai-backend   
  ports:
    - protocol: TCP
      port: 8000     
      targetPort: 8000
